# docker-compose.yml
version: "3"
services:
  frontend:
    container_name: crumble
    build: ./crumble
    ports:
      - 80:3000
  web:
    container_name: skynet
    build: ./skynet
    ports:
      - "8000:8000"
