# docker-compose.yml
version: "3"
services:
  database:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
  web:
    depends_on:
      - database
    container_name: skynet
    build: ./skynet
    ports:
      - 8000:8000
    environment:
      MONGO_URI: mongodb://database:27017
      DATABASE_NAME: memories
      GPT_API_KEY:
  frontend:
    depends_on:
      - web
    container_name: crumble
    build: ./crumble
    ports:
      - 80:3000
volumes:
  mongodata: