# docker-compose.yml
version: "3"
services:
  web:
    container_name: skynet
    build: ./skynet
    ports:
      - "8000:8000"
  frontend:
    depends_on:
      - web
    container_name: crumble
    build: ./crumble
    ports:
      - 80:3000
