name: Prod Release
# only trigger on tags, `verify` has already been triggered by push to PR
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and Run
        run: |
          docker-compose down
          docker-compose up -d --env GPT_API_KEY=${{ secrets.GPT_API_KEY }}
